name: Python 3.9.2

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.2
      uses: actions/setup-python@v1
      with:
        python-version: 3.9.2
    - name: Install dependencies
      run: |
        make install-gcp
    - name: Lint with pylint
      run: |
        make lint
    - name: Test with pytest
      run: |
        make test
    - name: Format code
      run: |
        make format
